#!/usr/bin/env bash

cd redefine-tests/ECU_KERNELS
for d in ./*/
do
     for i in $d*.c
     do
         echo "#########################################################"
         echo "make ref TARGET=$i"
         make ref TARGET=$i
         echo "#########################################################"
     done
 done
