//def int_createinst: Intrinsic <[llvm_i32_ty], [llvm_i32_ty, llvm_i32_ty], [IntrReadArgMem]>;
//def int_falloc: Intrinsic <[llvm_i32_ty], [llvm_i32_ty], [IntrReadArgMem]>;
//def int_fbind: Intrinsic <[], [llvm_i32_ty, llvm_i32_ty, llvm_i32_ty], [IntrReadArgMem]>;
//def int_fdelete: Intrinsic <[], [llvm_i32_ty, llvm_i32_ty], [IntrReadArgMem]>;
//def int_writecmp: Intrinsic <[], [llvm_i32_ty, llvm_i32_ty, llvm_i32_ty], [IntrReadArgMem]>;
//def int_writecm: Intrinsic <[], [llvm_i32_ty, llvm_i32_ty, llvm_i32_ty], [IntrReadArgMem]>;
//def int_sync: Intrinsic <[], [llvm_i32_ty, llvm_i32_ty, llvm_i32_ty], [IntrReadArgMem]>;
